<?php 
    $item = $block->getEditRecord();
    // echo "<pre>";
    // print_r($item);
    // echo "</pre>";
    // die;
?>
<h1><?php echo $this->showUserForm(); ?></h1>
<form class="form contact"
      action="<?php echo $block->getUrl('learning/index/update'); ?>"
      id="contact-form"
      method="post"
     enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <div class="field name required">
            <label class="label" for="fullname"><span><?= $block->escapeHtml(__('Họ tên')) ?></span></label>
            <div class="control">
                <input name="fullname" id="fullname" value ="<?= $item['fullname'] ?>" title="<?= $block->escapeHtmlAttr(__('Fullname')) ?>"  class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="class"><span><?= $block->escapeHtml(__('Lớp')) ?></span></label>
            <div class="control">
                <input name="class" id="class" value ="<?= $item['class'] ?>" title="<?= $block->escapeHtmlAttr(__('Class')) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="nation"><span><?= $block->escapeHtml(__('Địa chỉ')) ?></span></label>
            <div class="control">
                <input name="nation" id="nation" value ="<?= $item['nation'] ?>" title="<?= $block->escapeHtmlAttr(__('address')) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div> 
        <div class="field name required">
            <label class="label" for="sex"><span><?= $block->escapeHtml(__('Giới tính')) ?></span></label>
            <div class="control">
                <select name="sex" class="input-text">
                    <option value = '1' <?= ($item['sex'] == "1") ?  "selected='true'" : '' ?>>Nam</option>
                    <option value = '0' <?= ($item['sex'] == "0") ?  "selected='true'" : '' ?>>Nữ</option>
                </select>
            </div>
        </div> 
        <div class="field name required">
            <label class="label" for="archive""><span><?= $block->escapeHtml(__('Thành tích')) ?></span></label>
            <div class="control">
                <input name="archive" id="archive" value ="<?= $item['archive'] ?>" title="<?= $block->escapeHtmlAttr(__('archive')) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div> 
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="id" id="id" value="<?= $item['id'] ?>" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Save')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Save')) ?></span>
            </button>
        </div>
    </div>
</form>
<script src="https://cdn.ckeditor.com/4.11.2/standard/ckeditor.js"></script>
<script>CKEDITOR.replace( 'content' );</script>